# -*- coding: utf-8 -*-
"""Step_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WAV0QM8_gETfePvfvSsdtlTzbp2lDnWp
"""

import pandas as P

Data = P.read_csv("Car_Data.csv")

Data = Data.dropna()

print(Data)

Data = Data.drop_duplicates()

print(Data)

print(Data.columns)



Data = Data.copy()

Data ["Drive"] = Data ["Drive"].str.upper()

print(Data)

Data.to_csv("Car_Data_2.csv")