# -*- coding: utf-8 -*-
"""Step_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQ_fBcTQK9m8GJEn1Nvx70e27WZY4RqV
"""

import pandas as P

D = P.read_csv("Car_Data_2.csv")

print(D.columns)

D ["Age"] = 2026 - D ["Year"]

H = D ["Age"].head ()

print (H)

Save_File = D.to_csv ("Car_Data_3.csv")