# -*- coding: utf-8 -*-
"""Step 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZjNJGZTsYByRdSouSIZDrYNuTmUuCNS
"""

import pandas as P

Data = P.read_csv("Car_Data.csv")

print(Data.shape)

print(Data.columns)

print(Data.dtypes)

print(Data.describe())

print(Data.isnull().sum())

print(Data.duplicated().sum())